### ISSUE TITLE
Run docker image

### ISSUE THREAD

**Issue by Marie59** [gher-uliege/DIVAnd-jupyterhub#3]
I am trying to run the docker image after building it to use it in a jupytherhub locally. And when I launch the run command I get this message: 
`Customizing authentication via ServerApp.login_handler_class=<class 'jupyterhub.singleuser.mixins.make_singleuser_app.<locals>.JupyterHubLoginHandler'> is deprecated in Jupyter Server 2.0. Use ServerApp.identity_provider_class. Falling back on legacy authentication.
JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?`
Maybe it's coming from the jupyterhub/singleuser:3.1 image and we could use a different one ?

**Comment by ctroupin** [comment]
Thanks Marie!
Do you mean: we could try to update `jupyterhub/singleuser:4.0.0b2` to a more recent version (for instance `jupyterhub/singleuser:4.0.0b2`)?

**Comment by Alexander-Barth** [comment]
Apparently, if one wants to by-pass the multi-user JupyterHub, one can use this: 

```
docker run -it  -p 8888:8888  abarth/divand-jupyterhub:latest  jupyter-lab
```

It seems that JUPYTERHUB_API_TOKEN is set automatically when you start the notebook from jupyterhub.

**Comment by Marie59** [comment]
I have spoken with a galaxy coworker and I think he found what is the issue about the permissions. We need to adapt the `run.sh` file.
Would you like me to open a new PR for that with a proposition for the run.sh @Alexander-Barth and @ctroupin ? (I already started something and I am testing it)

**Comment by ctroupin** [comment]
Yes it's probably the besst to start a PR and we can see what is proposed.

**Comment by Marie59** [comment]
I think we can now close this issue and follow up on this PR https://github.com/gher-uliege/DIVAnd-jupyterhub/pull/5.
